spring:
  application:
    name: shiroWeb1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.143:3306/shiro?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: wall,stat,slf4j
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 127.0.0.1
    port: 6379
  aop:
    proxy-target-class: true
logging:  #log
  path: D:/sringbootWorkspace/shirologs
  level: debug
server:
  port: 9000
